version: '2'
volumes:
  db:
  node_modules:
  deps:
  build:

services:
  db:
    image: instedd/ask-mysql:5.7
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  ports:
      - 3306:3306
  app:
    command: elixir --sname server -S mix phoenix.server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /app
    depends_on:
      - db
    volumes:
      - './:/app'
      - 'deps:/app/deps'
      - 'build:/app/_build'
    environment:
      DATABASE_HOST: db
      HTTP_PORT: 80
      TERM: xterm
      NUNTIUM_BASE_URL: http://192.168.99.100:3000
      NUNTIUM_GUISSO_BASE_URL: https://login.example.com
      NUNTIUM_CLIENT_ID: clientID
      NUNTIUM_CLIENT_SECRET: clientSecret
      NUNTIUM_APP_ID: nuntium.example.com
    ports:
      - 4000:80

  webpack:
    build:
      context: ./
      dockerfile: Dockerfile.webpack
    command: yarn run watch
    restart: always
    working_dir: /app
    stop_signal: SIGKILL
    volumes:
      - './:/app'
      - 'deps:/app/deps'
      - 'node_modules:/app/node_modules'

  ngrok:
    image: wernight/ngrok
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: 'app:80'
